-- Pre-migration for rc/0.1.0 / v0.0.5
-- Timezone standardization
--
-- Postgres stores TIMESTAMPTZ internally in UTC, but functions like now(), CURRENT_DATE,
-- and date casts depend on the session TimeZone.
--
-- The backend connection now forces session timezone to Brazil:
--   options = -c TimeZone=America/Sao_Paulo
--
-- Optional (infra-level) hardening:
-- You may also set the default timezone at the database/role level in production,
-- so any client (psql, cron jobs, etc.) runs in the same timezone.
--
-- Examples (choose ONE, adjust names):
--   ALTER DATABASE inbota SET TimeZone TO 'America/Sao_Paulo';
--   ALTER ROLE vxfontes SET TimeZone TO 'America/Sao_Paulo';
--
-- No DDL required here because database name/role varies per environment.
